### ISSUE TITLE
Add "master" option for Drupal 8 drush

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox-plugin-drush#11]
I believe Drupal 8 uses the "master" branch and doesn't have a numbered version: https://github.com/drush-ops/drush

Once we add a Drupal 8 create option, guessing we'll want that @pirog?

_Edit:_ Guess we already have the D8 create option, so I suppose we should just do this at our earliest convenience.

**Comment by pirog** [comment]
yeah def, we should get drush 8 in there along with the drupal console

On Fri, Jul 17, 2015 at 4:23 PM, reynoldsalec notifications@github.com
wrote:

> I believe Drupal 8 uses the "master" branch and doesn't have a numbered
> version: https://github.com/drush-ops/drush
> 
> Once we add a Drupal 8 create option, guessing we'll want that @pirog
> https://github.com/pirog?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalabox/kalabox-plugin-drush/issues/11.

## 

Mike

## 

Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9
, Linkedin
http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9,
and Facebook
http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9

**Comment by pirog** [comment]
going to close this since upgrading terminus is in the next sprint
