### ISSUE TITLE
Generate kalabox SSH keys for relevant services like Pantheon

### ISSUE THREAD

**Issue by UTANdev** [kalabox/kalabox-plugin-drush#7]
Every time I run a Drush command, I have to enter an SSH key passphrase:

```
C:\Users\UTAN\VirtualBox VMs\mtms\code>kbox drush cc all
info: DOCKER => Creating RUN container.
info: DOCKER => Attaching RUN container.
info: DOCKER => Starting RUN container.
Enter passphrase for /ssh/.ssh/id_rsa:
Identity added: /ssh/.ssh/id_rsa (/ssh/.ssh/id_rsa)
'all' cache was cleared.                                                                   [success]
info: DOCKER => RUN container shutting down.
```

And the next time I run a Drush command — same thing. Where can I store the passphrase to Kalabox automatically uses it?

**Comment by pirog** [comment]
I'm not sure you can save an ssh passphrase but you can create a key without a passphrase which might be the best option at this point. 

at some point maybe we can integrate with keychain and other password storing apps to do this.

**Comment by pirog** [comment]
Have you tried doing this sans-passphrase?

**Comment by UTANdev** [comment]
I've had to leave the project aside until next week. If no update is posted within two weeks, then a key without passphrase worked fine.

Since I'm running Drush commands on my local dev site, the lack of passphrase isn't a problem — if my PC is hacked, then my local dev is, too. I do feel uneasy at the thought of running Drush commands on remote sites, though. Isn't that the point of never using ssh keys without passphrases on production sites? Your feedback would be appreciated.

**Comment by pirog** [comment]
There are obviously varying levels of tolerance to this idea. When you say "run drush commands remotely" do you mean via kbox or with your local drush or what?

SSH key handling is definitely something we need to improve. Wouldn't be tough to have keys for specific purposes ie you could keep your normal key passphrased but maybe you have a separate kalabox.id_rsa that isn't. 

At the end of the day though if you want to passphrase your ssh key you are going to have to deal with increased interactivity.

**Comment by pirog** [comment]
https://github.com/ericvicenti/ssh-keygen
https://www.npmjs.com/package/ssh-fingerprint
https://github.com/pantheon-systems/terminus/blob/master/terminus.user.api.inc

**Comment by tschet** [comment]
I think I'm seeing the same problem, but maybe I'm missing something here. I have an ssh key, and it works as expected with everything but Kalabox. Kalabox always asks for the passphrase, every single time. All my other command line tools ask for it once, but Kalabox asks for it again and again. I've tried an ssh key with no passphrase, but it still asks. I just have to hit enter on an empty line instead of typing something. Still annoying. Is there a way to set some configuration so I don't have to use a passphrase, empty or otherwise?

**Comment by pirog** [comment]
We will manage all the ssh key stuff for you in the next release which is dropping next week. 

Until then yeah unfortunately you have to enter it multiple times. :(

**Comment by tschet** [comment]
No problem. I'm happy to hear it's working as expected. :)

**Comment by pirog** [comment]
Yeah def! Thanks for your patience as we work to get a stable release out!

On Fri, Sep 18, 2015 at 1:38 PM, Douglas Tschetter <notifications@github.com

> wrote:
> 
> No problem. I'm happy to hear it's working as expected. :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kalabox/kalabox-plugin-drush/issues/7#issuecomment-141562371
> .

## 

Mike

## 

Mike Pirog
Co-Founder, Products
http://kalamuna.com

Stay connected with Kalamuna on: Twitter
http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Ftwitter.com%2Fkalamuna&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9
, Linkedin
http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.linkedin.com%2Fcompany%2F2584606&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9,
and Facebook
http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs1pwYhxW8qlTmx64kckdW8pTc_456dT6hf3BRzQ602?t=http%3A%2F%2Fwww.facebook.com%2Fkalamunatech&si=5428072445640704&pi=f16b515d-1f50-46c7-aebf-11a0c79916b9
